
INSERT INTO Variedades
(NombreComun, NombreCientifico, Descripcion, PorteId, GrainSizeId, AltitudOptimaM,
 YieldPotentialId, QualityLevelId, Obtentor, Familia, GrupoGenetico, TiempoCosecha,
 Maduracion, NotasNutricion, DensidadSiembra, CreadoPor)
VALUES
('Tipica', 'Coffea arabica (Tipica)', 'Variedad tradicional cultivada en Colombia, conocida por su alta calidad en taza pero con baja resistencia a enfermedades.', 
 (SELECT Id FROM Porte WHERE Nombre='Medio'),
 (SELECT Id FROM TamanoGrano WHERE Nombre='Medio'),
 1600,
 (SELECT Id FROM PotencialRendimiento WHERE Nombre='Medio'),
 (SELECT Id FROM NivelCalidad WHERE Nivel=5),
 'Introducida en Colombia',
 'Rubiaceae',
 'Arabica',
 'Media',
 'Maduracion media',
 'Requiere nutricion balanceada',
 '3000-4000 plantas/ha',
 NULL),

('Borbon', 'Coffea arabica (Borbon)', 'Variedad tradicional de alta calidad, buen cuerpo y acidez balanceada, pero susceptible a roya.', 
 (SELECT Id FROM Porte WHERE Nombre='Medio'),
 (SELECT Id FROM TamanoGrano WHERE Nombre='Medio'),
 1600,
 (SELECT Id FROM PotencialRendimiento WHERE Nombre='Medio'),
 (SELECT Id FROM NivelCalidad WHERE Nivel=5),
 'Introducida desde Isla Reunion',
 'Rubiaceae',
 'Arabica',
 'Media',
 'Maduracion media',
 'Requiere nutricion media',
 '3000-4000 plantas/ha',
 NULL),

('Maragogipe', 'Coffea arabica (Maragogipe)', 'Variedad con granos muy grandes, bajo rendimiento pero excelente calidad de taza.', 
 (SELECT Id FROM Porte WHERE Nombre='Alto'),
 (SELECT Id FROM TamanoGrano WHERE Nombre='Grande'),
 1500,
 (SELECT Id FROM PotencialRendimiento WHERE Nombre='Bajo'),
 (SELECT Id FROM NivelCalidad WHERE Nivel=5),
 'Originaria de Brasil',
 'Rubiaceae',
 'Arabica',
 'Tardia',
 'Maduracion tardia',
 'Nutricion exigente',
 '2000-3000 plantas/ha',
 NULL),

('Caturra', 'Coffea arabica (Caturra)', 'Mutacion natural de Borbon, porte bajo, muy cultivada en Colombia por su adaptacion.', 
 (SELECT Id FROM Porte WHERE Nombre='Bajo'),
 (SELECT Id FROM TamanoGrano WHERE Nombre='Pequeno'),
 1600,
 (SELECT Id FROM PotencialRendimiento WHERE Nombre='Alto'),
 (SELECT Id FROM NivelCalidad WHERE Nivel=4),
 'Descubierta en Brasil, difundida por Cenicafe',
 'Rubiaceae',
 'Arabica',
 'Media',
 'Maduracion media',
 'Requiere fertilizacion frecuente',
 '4000-5000 plantas/ha',
 NULL),

('Variedad Colombia', 'Coffea arabica (Colombia)', 'Hibrido desarrollado por Cenicafe con resistencia a la roya y buena productividad.', 
 (SELECT Id FROM Porte WHERE Nombre='Medio'),
 (SELECT Id FROM TamanoGrano WHERE Nombre='Medio'),
 1500,
 (SELECT Id FROM PotencialRendimiento WHERE Nombre='Alto'),
 (SELECT Id FROM NivelCalidad WHERE Nivel=4),
 'Cenicafe',
 'Rubiaceae',
 'Arabica',
 'Media',
 'Maduracion uniforme',
 'Nutricion balanceada',
 '3000-4000 plantas/ha',
 NULL),

('Tabi', 'Coffea arabica (Tabi)', 'Hibrido desarrollado en Colombia con resistencia a la roya, combina Tipica, Borbon y Hibrido de Timor.', 
 (SELECT Id FROM Porte WHERE Nombre='Alto'),
 (SELECT Id FROM TamanoGrano WHERE Nombre='Medio'),
 1500,
 (SELECT Id FROM PotencialRendimiento WHERE Nombre='Medio'),
 (SELECT Id FROM NivelCalidad WHERE Nivel=4),
 'Cenicafe',
 'Rubiaceae',
 'Arabica',
 'Media',
 'Maduracion media',
 'Requiere nutricion media',
 '3000-4000 plantas/ha',
 NULL);

-- =========================
-- ROBUSTAS WCR
-- =========================

INSERT INTO Variedades
(NombreComun, NombreCientifico, Descripcion, PorteId, GrainSizeId, AltitudOptimaM,
 YieldPotentialId, QualityLevelId, Obtentor, Familia, GrupoGenetico, TiempoCosecha,
 Maduracion, NotasNutricion, DensidadSiembra, CreadoPor)
VALUES
('BP 534', 'Coffea canephora (BP 534)', 'Clon robusta de Indonesia, alta productividad y buena adaptacion en bajas altitudes.', 
 (SELECT Id FROM Porte WHERE Nombre='Bajo'),
 (SELECT Id FROM TamanoGrano WHERE Nombre='Medio'),
 300,
 (SELECT Id FROM PotencialRendimiento WHERE Nombre='Alto'),
 (SELECT Id FROM NivelCalidad WHERE Nivel=3),
 'Indonesia',
 'Rubiaceae',
 'Guinea x Congo',
 'Tardia',
 'Maduracion tardia',
 'Requiere nutricion alta',
 '2000-3000 plantas/ha',
 NULL),

('BP 936', 'Coffea canephora (BP 936)', 'Clon robusta de Indonesia con resistencia a plagas y alto rendimiento.', 
 (SELECT Id FROM Porte WHERE Nombre='Bajo'),
 (SELECT Id FROM TamanoGrano WHERE Nombre='Medio'),
 300,
 (SELECT Id FROM PotencialRendimiento WHERE Nombre='Alto'),
 (SELECT Id FROM NivelCalidad WHERE Nivel=3),
 'Indonesia',
 'Rubiaceae',
 'Guinea x Congo',
 'Tardia',
 'Maduracion tardia',
 'Requiere nutricion alta',
 '2000-3000 plantas/ha',
 NULL),

('BP 939', 'Coffea canephora (BP 939)', 'Clon robusta de Indonesia ampliamente cultivado, con buena tolerancia a sequia.', 
 (SELECT Id FROM Porte WHERE Nombre='Bajo'),
 (SELECT Id FROM TamanoGrano WHERE Nombre='Medio'),
 300,
 (SELECT Id FROM PotencialRendimiento WHERE Nombre='Alto'),
 (SELECT Id FROM NivelCalidad WHERE Nivel=3),
 'Indonesia',
 'Rubiaceae',
 'Guinea x Congo',
 'Tardia',
 'Maduracion tardia',
 'Requiere nutricion alta',
 '2000-3000 plantas/ha',
 NULL),

('BRS 1216', 'Coffea canephora (BRS 1216)', 'Variedad robusta desarrollada en Brasil, con excelente productividad.', 
 (SELECT Id FROM Porte WHERE Nombre='Medio'),
 (SELECT Id FROM TamanoGrano WHERE Nombre='Medio'),
 300,
 (SELECT Id FROM PotencialRendimiento WHERE Nombre='Excepcional'),
 (SELECT Id FROM NivelCalidad WHERE Nivel=3),
 'Brasil - EMBRAPA',
 'Rubiaceae',
 'Conilon',
 'Media',
 'Maduracion media',
 'Requiere fertilizacion intensiva',
 '2500-3500 plantas/ha',
 NULL),

('BRS 2336', 'Coffea canephora (BRS 2336)', 'Clon robusta brasileño con alto potencial de produccion y resistencia media a plagas.', 
 (SELECT Id FROM Porte WHERE Nombre='Medio'),
 (SELECT Id FROM TamanoGrano WHERE Nombre='Medio'),
 300,
 (SELECT Id FROM PotencialRendimiento WHERE Nombre='Alto'),
 (SELECT Id FROM NivelCalidad WHERE Nivel=3),
 'Brasil - EMBRAPA',
 'Rubiaceae',
 'Conilon',
 'Media',
 'Maduracion media',
 'Requiere fertilizacion alta',
 '2500-3500 plantas/ha',
 NULL);